# Generated by Django 2.2.4 on 2019-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=1009)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=1009)),
                ('address', models.CharField(max_length=1500)),
                ('city', models.CharField(max_length=1999)),
                ('district', models.CharField(max_length=1999)),
                ('state', models.CharField(max_length=1000)),
                ('bank_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
